name: Build and Deploy Flutter application
on: [push]
jobs:
  build_android_flutter_app:
    name: Build Android application using Flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2
        name: Preparing Flutter SDK
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
      - run: |
          flutter build apk --build-name=1.0.0-${{github.sha}} --build-number=${{github.run_number}} --verbose
        name: Building application
      - uses: actions/upload-artifact@v3
        name: Archive production artifacts
        with:
          name: android-app-1.0.0-${{github.run_number}}-${{github.sha}}
          path: |
            build/app/outputs/apk/release/app-release.apk