name: Build and Deploy Flutter application
on: [push]
jobs:
  build_android_flutter_app:
    name: Build Android application using Flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2
        name: Preparing Flutter SDK
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
          -run: flutter analyze
          name: Analyzing source
          build_android_flutter_app:
    name: Build Android application using Flutter
    runs-on: ubuntu-latest
    needs: [analyze_flutter_app]
    steps:
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2
        name: Preparing Flutter SDK
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
      - run: |
          flutter build apk --build-name=1.0.0-${{github.sha}} --build-number=${{github.run_number}} --verbose
        name: Building application
      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        name: Uploading production artifact to Firebase App Distribution
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk
  build_ios_flutter_app:
    name: Build iOS application using Flutter
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2
        name: Preparing Flutter SDK
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
      - run: |
          ./generate_ios_plist.sh
          flutter build ipa --build-name=1.0.0-${{github.sha}} --build-number=${{github.run_number}} --export-options-plist=ios/app-ios-export.plist  --verbose
        name: Building application
      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        name: Uploading production artifact to Firebase App Distribution
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/ios/ipa/flutter_tour.ipa